controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController


mecanum_drive_controller:
  ros__parameters:
    use_sim_time: true

    front_left_wheel_command_joint_name: "front_left_joint"
    front_right_wheel_command_joint_name: "front_right_joint"
    rear_left_wheel_command_joint_name: "back_left_joint"
    rear_right_wheel_command_joint_name: "back_right_joint"

    kinematics:
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.275

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true

    pose_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

    # ðŸ”¥ These 2 lines make teleop work
    use_stamped_cmd_vel: false
    velocity_command_topic: "/cmd_vel"
