teleop_twist_joy_node:
  ros__parameters:
    axis_linear.x: 1
    axis_linear.y: 0
    axis_angular.yaw: 2

    scale_linear.x: 0.4
    scale_linear.y: 0.4
    scale_angular.yaw: 0.9

    enable_button: 5           # RB on most joysticks
    enable_turbo_button: 4     # LB on most joysticks

    publish_stamped_twist: false
    cmd_vel_topic: "/cmd_vel"
