slam_toolbox:
  ros__parameters:
    use_sim_time: true 
    # load_map: true
    # serialized_map_path: maps/map.yaml
    
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    odom_frame: odom #checked 
    map_frame: map #checked
    base_frame: base_link #checked
    scan_topic: /scan #checked
    provide_odom_frame: false
    publish_tf: true
    
    # SLAM mode
    mode: mapping
    
    # Debug
    debug_logging: false
    throttle_scans: 2
    
    # Transform publishing
    transform_publish_period: 0.02
    map_update_interval: 5.0  
    resolution: 0.05
    max_laser_range: 15.0
    minimum_time_interval: 0.1  # earlier 0.3
    
    transform_timeout: 5.0  
    tf_buffer_duration: 60.0 
    
    message_filter_queue_size: 100  
    
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2  
    minimum_travel_heading: 0.1   
    scan_buffer_size: 30  
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    
    # Loop closure
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.02
    angle_variance_penalty: 0.02
    fine_search_angle_offset: 0.08
    coarse_search_angle_offset: 0.3
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.0001
    minimum_distance_penalty: 0.0001
    use_response_expansion: true